[versions]
androidx-compose = "1.2.0-alpha06"
androidx-navigation = "2.4.1"

[libraries]
# Common libs
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.7.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.4.1" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.0" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.3.2" }

# Views-related libs
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version = "1.4.1"}
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.0-alpha01" }
binding-delegate = { module = "com.github.Zhuinden:fragmentviewbindingdelegate-kt", version = "1.0.0" }
google-material = { module = "com.google.android.material:material", version = "1.5.0" }

# Compose-related libs
androidx-activity = { module = "androidx.activity:activity-compose", version = "1.4.0" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx.compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha08" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }

[bundles]
androidx-foundation = [
    "androidx-appcompat",
    "androidx-core",
    "androidx-lifecycle"
]
androidx-navigation-views = [
    "androidx-navigation-fragment",
    "androidx-navigation-ui"
]
compose-mobile = [
    "androidx-activity",
    "compose-animation",
    "compose-foundation",
    "compose-material3",
    "compose-ui"
]
compose-lib = [
    "compose-animation",
    "compose-foundation",
    "compose-ui"
]
